export default [
  {
    img: "nick.jpg",
    rating: "4.2",
    reviewCount: 4,
    country: "Canada",
    title: "Golden hour with Nick S.",
    price: 49,
  },
  {
    img: "sumire.jpg",
    rating: "4.7",
    reviewCount: 7,
    country: "Japan",
    title: "Sumire's Gardening Tales",
    price: 35,
  },
  {
    img: "matt.jpg",
    rating: "4.9",
    reviewCount: 9,
    country: "Colombia",
    title: "A Perfect Cup by Matt",
    price: 42,
  },
  {
    img: "tessa.jpg",
    rating: "4.6",
    reviewCount: 6,
    country: "Spain",
    title: "A Guitar Journey feat. Tessa",
    price: 46,
  },
  {
    img: "oliver.jpg",
    rating: "4.2",
    reviewCount: 5,
    country: "USA",
    title: "Wild Waves with Oliver",
    price: 69,
  },
  {
    img: "natalie.jpg",
    rating: "4.3",
    reviewCount: "6",
    country: "Canada",
    title: "Free your Mind with Natalie",
    price: 49,
  },
  {
    img: "robbie.jpg",
    rating: "5.0",
    reviewCount: "5",
    country: "USA",
    title: "Camera and I by Robbie",
    price: 50,
  },
];
